### ISSUE TITLE
Offline Message from Maryann Martone: I notice we don't have the NeuroNames I...

### ISSUE THREAD

**Issue by SciCrunch-Synapse** [SciCrunch/NIF-Ontology#140] opened 2018-06-19 20:29 UTC
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#23816](https://scicrunch.zendesk.com/agent/tickets/23816)
**Group:** Support
**Requester:** mmartone@ucsd.edu
**Issue escalated by:** SciCrunch
**URL:** 

**Original ticket description:**

<blockquote><div class="zd-comment">
<p>From: Maryann Martone &lt;<a href="mailto:mmartone@ucsd.edu" rel="noreferrer">mmartone@ucsd.edu</a>&gt;
<br>Phone: 
<br>Location: La Jolla, United States
<br>URL: <a href="https://scicrunch.org/scicrunch/interlex/view/ilx_0110082?searchTerm=nucleus" target="_blank" rel="nofollow noreferrer">https://scicrunch.org/scicrunch/interlex/view/ilx_0110082?searchTerm=nucleus</a>
<br>Department: </p>

<p>I notice we don't have the NeuroNames IDs in Neurolex.  They were all mapped, as far as I know.</p>

<p>----
<br>Zopim
<br><a href="https://www.zopim.com" target="_blank" rel="nofollow noreferrer">https://www.zopim.com</a></p>
</div></blockquote>

**Comment by tgbugs** [comment] 2019-04-16 03:19
Closing as duplicate of #125. We don't want to add these because many were [wrong](https://github.com/obophenotype/uberon/pull/1493)

**Closed by tgbugs** 2019-04-16 03:19 UTC
Labels: Zendesk
