### ISSUE TITLE
SAO labels are not visible in NPO file

### ISSUE THREAD

**Issue by memartone** [SciCrunch/NIF-Ontology#216] opened 2020-08-19 22:42 UTC
I am not seeing any labels associated with SAO terms
<img width="271" alt="Screen Shot 2020-08-19 at 3 39 54 PM" src="https://user-images.githubusercontent.com/6580029/90697159-a0aa9f00-e232-11ea-9c8b-bc76828567b8.png">

**Comment by tgbugs** [comment] 2020-08-19 23:04
Neuron below it is an SAO term. The issue is that we cut off the hierarchy at a certain point and the parent classes beyond that cut only appear as identifiers. I'll see if I can add just their labels to the graph.

**Comment by memartone** [comment] 2020-08-20 17:58
So is Neuron a subclass of Nervous system cell?

**Comment by tgbugs** [comment] 2020-08-20 18:27
This is now fixed in the version I just pushed.

Yes, neuron is a subclass of Nervous system cell in the SAO hierarchy.

**Closed** 2020-08-20 18:34 UTC
