### ISSUE TITLE
INC synonym

### ISSUE THREAD

**Issue by SciCrunch-Synapse** [SciCrunch/NIF-Ontology#105] opened 2017-05-15 19:39 UTC
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#16330](https://scicrunch.zendesk.com/agent/tickets/16330)
**Priority:** N/A
**Group:** Support
**Requester:** abandrowski@ucsd.edu
**Organization:** N/A
**Assignee:** N/A

**Original ticket description:**

<blockquote><div class="zd-comment">
<p dir="auto">So I don't see inc in my synonym list for Cell Signaling.
<br>Tom can you please check your synonym list in scigraph?</p>

<p dir="auto">On Wed, May 10, 2017 at 12:05 AM, SciCrunch &lt;<a href="mailto:support@scicrunch.zendesk.com" rel="noreferrer">support@scicrunch.zendesk.com</a>&gt; wrote:</p>

<p dir="auto">Maryann Martone submitted a help request on 2017-05-09T21:05:26-07:00. To reply to the user please click on this mail link. All responses will be logged via ZenDesk if the subject contains the Ticket Number and SciCrunch support at ZenDesk is a cc. There maybe some issues with gmail using the mailto tag properly so please make sure the appropriate CC and Subject are included:</p>

<p dir="auto">CC: <a href="mailto:rii-help@scicrunch.com" rel="noreferrer">rii-help@scicrunch.com</a></p>

<p dir="auto">Subject: Ticket <a href="/agent/tickets/16323" target="_blank" rel="ticket">#16323</a> - Offline Message from Maryann Martone: inc appears to be a synonym for "Cell S...</p>

<p dir="auto">Help Request:</p>

<p dir="auto">Maryann Martone</p>

<p dir="auto">May 9, 21:05</p>

<p dir="auto">From: Maryann Martone &lt;<a href="mailto:mmartone@ucsd.edu" rel="noreferrer">mmartone@ucsd.edu</a>&gt;
<br>Phone:
<br>Location: San Diego, United States
<br>URL: <a href="https://scicrunch.org/resources/Antibodies/source/nif-0000-07730-1/search?q=%22Cell%20Signaling%20Technology%22&amp;l=%22Cell%20Signaling%20Technology%22%20&amp;facet%5B%5D=Vendor:Cell%20Signaling%20Technology" rel="nofollow noreferrer" target="_blank">https://scicrunch.org/resources/Antibodies/source/nif-0000-07730-1/search?q=%22Cell%20Signaling%20Technology%22&amp;l=%22Cell%20Signaling%20Technology%22%20&amp;facet[]=Vendor:Cell%20Signaling%20Technology</a> (<a href="https://scicrunch.org/resources/Antibodies/source/nif-0000-07730-1/search?q=%22Cell%20Signaling%20Technology%22&amp;l=%22Cell%20Signaling%20Technology%22%20&amp;facet%5B%5D=Vendor:Cell%20Signaling%20Technology" rel="nofollow noreferrer" target="_blank">https://scicrunch.org/resources/Antibodies/source/nif-0000-07730-1/search?q=%22Cell%20Signaling%20Technology%22&amp;l=%22Cell%20Signaling%20Technology%22%20&amp;facet%5B%5D=Vendor:Cell%20Signaling%20Technology</a>)
<br>Department:</p>

<p dir="auto">inc appears to be a synonym for "Cell Signaling Technology". That causes a lot of search problems. Can we remove it?</p>

<p dir="auto">----
<br>Zopim
<br><a href="https://www.zopim.com" rel="nofollow noreferrer" target="_blank">https://www.zopim.com</a></p>

<p dir="auto">This email is a service from SciCrunch. Delivered by Zendesk (<a href="http://www.zendesk.com" rel="nofollow noreferrer" target="_blank">http://www.zendesk.com</a>) .</p>

<p dir="auto">--
<br>Anita Bandrowski, Ph.D.
<br>All Key Biological Resources Deserve #RRID
<br> 
<br>9500 Gillman Dr.<a href="/agent/tickets/0446" target="_blank" rel="ticket">#0446</a>
<br>La Jolla, CA 92093-0446
<br>orcid.org/0000-0002-5497-0243</p>
</div></blockquote>

**Comment by tgbugs** [comment] 2017-05-15 20:57
I have a temporary fix for this already. The issue is that there are a number of company names with a comma in the title and we use comma as an implicit field separator in the registry.

**Comment by tgbugs** [comment] 2017-05-15 20:59
@jgrethe @fivebillionmph To finish this fix I do need to know what needs to happen to safely update the production scigraph servers. Did we ever work out a reasonable way to do that without downtime?

**Comment by jgrethe** [comment] 2017-05-15 21:17
If James is routing through SciCrunch NGINX, I think we can have primary and secondaries setup between the two servers so that when we take one down it fails overs.

Prod UI:  Primary 1, Primary 2
Prod Services: Primary 2, Primary 1

**Comment by tgbugs** [comment] 2017-05-16 21:19
This has been fixed properly and pushed to production.

**Closed by tgbugs** 2017-05-16 21:19 UTC
