### ISSUE TITLE
Obsolete brain of rodent

### ISSUE THREAD

**Issue by memartone** [SciCrunch/NIF-Ontology#67] opened 2016-08-03 00:29 UTC
In Knowledge Space, we have the class "Obsolete brain of rodent" from UBERON:  UBERON:0023939.  I'm assuming this is an obsolete class.  We should probably have a boneyard for obsolete classes along with a note as to why the classes were or were not deprecated.

**Comment by jgrethe** [comment] 2016-08-03 00:35
It should be a hidden bone yard as users may not understand the ways of ontology maintenance

**Comment by tgbugs** [comment] 2016-08-04 00:18
closing as duplicate of KS issues #51

**Closed by tgbugs** 2016-08-04 00:18 UTC
Labels: duplicate
